[metadata]
name = benchmarking
license = MIT
description = A collection of benchmarking functions for optimization algorithms
long_description = file: README.md
author = Zachery Crandall
author_email = zachcran@iastate.edu
# classifiers=
#    <classifier 1>
#    <classifier 2>
#    <...>
#    <classifier m>

[options]
packages = find:
package_dir =
    =src
include_package_data = True

[options.packages.find]
where=src
